### ISSUE TITLE
Not work for Source Sans Pro font

### ISSUE THREAD

**Issue by rayronvictor** [CardinalNow/google-fonts-bower-proxy#1]
I run `bower install --save https://google-fonts.azurewebsites.net/googleFonts/sourceSansPro?family=Source+Sans+Pro:400,200,300,600,700` and I get the following messages and files:

![captura de tela 2015-09-15 as 11 12 01](https://cloud.githubusercontent.com/assets/1683922/9878753/b01b5692-5b9a-11e5-8529-6ac7e677434b.png)
![captura de tela 2015-09-15 as 11 12 20](https://cloud.githubusercontent.com/assets/1683922/9878750/ac6bec78-5b9a-11e5-9a91-adbfe04bf913.png)

This is the content of `.bower.json` file:
![captura de tela 2015-09-15 as 11 13 08](https://cloud.githubusercontent.com/assets/1683922/9878786/d9cedd88-5b9a-11e5-93c7-39b85c0d13e3.png)

And this is the content of `index` file:
![captura de tela 2015-09-15 as 11 14 45](https://cloud.githubusercontent.com/assets/1683922/9878810/fdefb4e4-5b9a-11e5-8982-a7ade15176b4.png)

Also, don't work for the Open Sans Condensed:
`bower install --save https://google-fonts.azurewebsites.net/googleFonts/openSansCondensed?family=Open+Sans+Condensed:300
`

When I get the Open Sans font all works well. May be that fonts with names with 3 words are failing

**Comment by rayronvictor** [comment]
Apparently, the `index` file is a zip file.

**Comment by supersaiyen** [comment]
It looks like i was only replacing the first "+" in the file name when downloading the zip, and bower cant un-zip a file with a + in its name. Try it now, and be sure to clean your bower cache.

**Comment by rayronvictor** [comment]
Thanks! Now it's working.
