### ISSUE TITLE
Package name is ignored ?

### ISSUE THREAD

**Issue by ajoah** [CardinalNow/google-fonts-bower-proxy#4]
Hi :)

Apparently the name of package given in the URL is totally ignored.

Example :
`bower install --save https://google-fonts.azurewebsites.net/googleFonts/example?family=Open+Sans`

Result in bower.json : 
`"openSans": "https://google-fonts.azurewebsites.net/googleFonts/example?family=Open+Sans"`
instead of 
`"example": "https://google-fonts.azurewebsites.net/googleFonts/example?family=Open+Sans"`

And indeed if we look at your code, it use only the family name for package name :

```javascript
var indexOfFamilySeperator = req.originalUrl.indexOf(":");
if(indexOfFamilySeperator<0){
	indexOfFamilySeperator = req.originalUrl.length;
}
var requestedFontName = req.originalUrl.substring(req.originalUrl.indexOf('=')+1, indexOfFamilySeperator);
requestedFontName = requestedFontName.replace(/\+/g, "");
requestedFontName = requestedFontName.charAt(0).toLocaleLowerCase()+requestedFontName.substr(1);
```
https://github.com/CardinalNow/google-fonts-bower-proxy/blob/9266e9f0497da1b745e55f45e9fcb2a2d6517b2c/googleFontsRepo.js#L23-L29

```javascript
dl.append(JSON.stringify({
"name": requestedFontName,
"main": [
"*.ttf",
"*.css"
]
}), { name: 'bower.json' });
```
https://github.com/CardinalNow/google-fonts-bower-proxy/blob/9266e9f0497da1b745e55f45e9fcb2a2d6517b2c/googleFontsRepo.js#L55-L61

**Comment by supersaiyen** [comment]
Fixed, though i have not deployed to azure yet. cfd837f4fdd9eb0c165ee315adbd69e8eed74547

**Comment by supersaiyen** [comment]
Azure deployment complete.

**Comment by ajoah** [comment]
Perfect, thank you 👍
